### PR TITLE
Fix holes distance from the edge

### PR DESCRIPTION
**Pull request by shatorofusuki**
Holes were protruding through the rim and were visible from the side. Author forgot about the shape of the sides of the disk

### CODE REVIEW

**Comment by hroncok** [comment]
Can you please show images so it's faster to understand?

**Comment by shatorofusuki** [comment]
Here is what I am talking about
screen shot 2017-03-13 at 18 11 54

**Comment by syky27** [comment]
I have rewarded you with a point.

Please delete your fork, we will be making this repository private for the next run of this course.

**Comment by shatorofusuki** [comment]
Thanks

**Comment by hroncok** [comment]
Actually this doesn't work either:

disc

**Comment by hroncok** [comment]
The real question here is: Should the `reduce_offset` be secret or should the holes be moved inside if `hight` is to high? There's a serious problem with this assignment. Maybe we can drop `reduce_offset` and say the center of those cylinder is in middle of the available space?

**Pull request merged**
