### PR TITLE
arm and mask: use for instead of duplicating code

### PR DESCRIPTION
**Pull request by nesro**
two or more, use a for

### CODE REVIEW

**Comment by hroncok** [comment]
Could you please fix the indentation?

**Comment by nesro** [comment]
Where it's broken?

**Comment by hroncok** [comment]
https://github.com/nesro/openscad-tasks/blob/9b7bea786695b0166afb1381e589b6205d17040e/lesson02/arm.scad#L36

**Comment by nesro** [comment]
Oh I'm sorry. I didn't notice that mask uses tabs and arm uses spaces.

**Comment by hroncok** [comment]
I just make sure it's consistent in one file. Consistency across several of them wasn't a priority :)

I don't get the commit message (fix.scad?). Could you just amend that to the commit that introduced the change?

**Pull request merged**
